CREATE TABLE [dbo].[ReportList]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[Name] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ReportList] ADD CONSTRAINT [PK_ReportList] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
