CREATE TABLE [dbo].[CDM_tblMENU_ITEM_MULTIPLE_PRINT_ZONES]
(
[itemID] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Print_Zone] [smallint] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CDM_tblMENU_ITEM_MULTIPLE_PRINT_ZONES] ADD CONSTRAINT [PK_CDM_tblMENU_ITEM_MULTIPLE_PRINT_ZONES] PRIMARY KEY CLUSTERED  ([itemID], [Print_Zone]) ON [PRIMARY]
GO
